name: Compile the example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
            lfs: true

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
            remote: true

      - name: Set up Python for installer
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      # TODO: simpler version in the future?
      - name: Install dependencies with sltx-install
        run: |
          python3 dep-helper/sltxinst sltx-dep.yml

      - name: Compile the example
        uses: xu-cheng/latex-action@v2
        with:
          root_file: example.tex

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f example.pdf
          git commit -m "Update PDF by workflow"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "gh-pages"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

